name: thunderingcat_core
description: "core library for thunderingcat"
version: 0.0.1
homepage: https://github.com/ThunderingCat/thunderingcat-core

environment:
  sdk: ^3.6.0
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
